import * as vscode from "vscode";
import type { SniparaClient } from "../client";
import type { SummaryType } from "../types";
import { requireConfigured } from "./helpers";

const SUMMARY_TYPE_OPTIONS: { label: string; value: SummaryType }[] = [
  { label: "Concise", value: "concise" },
  { label: "Detailed", value: "detailed" },
  { label: "Technical", value: "technical" },
  { label: "Keywords", value: "keywords" },
  { label: "Custom", value: "custom" },
];

export function registerSummaryCommands(
  context: vscode.ExtensionContext,
  client: SniparaClient
): void {
  // ─── Store Summary ────────────────────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("snipara.storeSummary", async () => {
      if (!(await requireConfigured(client))) return;

      const documentPath = await vscode.window.showInputBox({
        prompt: "Enter the document path to summarize",
        placeHolder: "docs/api.md",
      });
      if (!documentPath) return;

      const summary = await vscode.window.showInputBox({
        prompt: "Enter the summary text",
        placeHolder: "This document covers the REST API endpoints for authentication...",
      });
      if (!summary) return;

      const typePick = await vscode.window.showQuickPick(SUMMARY_TYPE_OPTIONS, {
        placeHolder: "Select summary type",
      });
      if (!typePick) return;

      await vscode.window.withProgress(
        {
          location: vscode.ProgressLocation.Notification,
          title: "Snipara: Storing summary...",
          cancellable: false,
        },
        async () => {
          try {
            const response = await client.storeSummary(documentPath, summary, {
              summaryType: typePick.value,
            });

            if (response.success && response.result) {
              vscode.window.showInformationMessage(
                `Summary stored: ${response.result.message} (ID: ${response.result.summary_id})`
              );
            } else {
              vscode.window.showErrorMessage(
                `Failed to store summary: ${response.error || "Unknown error"}`
              );
            }
          } catch (error) {
            vscode.window.showErrorMessage(
              `Snipara error: ${error instanceof Error ? error.message : "Unknown error"}`
            );
          }
        }
      );
    })
  );

  // ─── Get Summaries ────────────────────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("snipara.getSummaries", async () => {
      if (!(await requireConfigured(client))) return;

      const documentPath = await vscode.window.showInputBox({
        prompt: "Enter document path to filter (leave empty for all)",
        placeHolder: "docs/api.md",
      });

      await vscode.window.withProgress(
        {
          location: vscode.ProgressLocation.Notification,
          title: "Snipara: Loading summaries...",
          cancellable: false,
        },
        async () => {
          try {
            const response = await client.getSummaries({
              documentPath: documentPath || undefined,
            });

            if (response.success && response.result) {
              const result = response.result;
              const lines: string[] = [
                `# Summaries`,
                ``,
                `**Total:** ${result.total_count}`,
                ``,
              ];

              for (const s of result.summaries) {
                lines.push(`## ${s.document_path}`);
                lines.push(`**ID:** ${s.summary_id}`);
                lines.push(`**Type:** ${s.summary_type}`);
                lines.push(`**Created:** ${s.created_at}`);
                if (s.generated_by) {
                  lines.push(`**Generated By:** ${s.generated_by}`);
                }
                lines.push(``);
                lines.push(s.summary);
                lines.push(``);
                lines.push(`---`);
                lines.push(``);
              }

              const doc = await vscode.workspace.openTextDocument({
                content: lines.join("\n"),
                language: "markdown",
              });
              await vscode.window.showTextDocument(doc, { preview: true });
            } else {
              vscode.window.showErrorMessage(
                `Failed to load summaries: ${response.error || "Unknown error"}`
              );
            }
          } catch (error) {
            vscode.window.showErrorMessage(
              `Snipara error: ${error instanceof Error ? error.message : "Unknown error"}`
            );
          }
        }
      );
    })
  );

  // ─── Delete Summary ───────────────────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("snipara.deleteSummary", async () => {
      if (!(await requireConfigured(client))) return;

      const summaryId = await vscode.window.showInputBox({
        prompt: "Enter the summary ID to delete",
        placeHolder: "sum_...",
      });
      if (!summaryId) return;

      const confirm = await vscode.window.showWarningMessage(
        `Are you sure you want to delete summary "${summaryId}"?`,
        { modal: true },
        "Delete"
      );
      if (confirm !== "Delete") return;

      await vscode.window.withProgress(
        {
          location: vscode.ProgressLocation.Notification,
          title: "Snipara: Deleting summary...",
          cancellable: false,
        },
        async () => {
          try {
            const response = await client.deleteSummary({ summaryId });

            if (response.success && response.result) {
              vscode.window.showInformationMessage(
                `Summary deleted: ${response.result.message}`
              );
            } else {
              vscode.window.showErrorMessage(
                `Failed to delete summary: ${response.error || "Unknown error"}`
              );
            }
          } catch (error) {
            vscode.window.showErrorMessage(
              `Snipara error: ${error instanceof Error ? error.message : "Unknown error"}`
            );
          }
        }
      );
    })
  );
}
